// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: quDeq6xe5KMiTCfKiiLfyW
// Component: tAA3tg-kIQ8L

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: gcpmzTU7M7CU/component
import { ParallaxWrapper } from "@plasmicpkgs/react-scroll-parallax";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: quDeq6xe5KMiTCfKiiLfyW/projectcss
import sty from "./PlasmicContactpage.module.css"; // plasmic-import: tAA3tg-kIQ8L/css

createPlasmicElementProxy;

export type PlasmicContactpage__VariantMembers = {};
export type PlasmicContactpage__VariantsArgs = {};
type VariantPropType = keyof PlasmicContactpage__VariantsArgs;
export const PlasmicContactpage__VariantProps = new Array<VariantPropType>();

export type PlasmicContactpage__ArgsType = {};
type ArgPropType = keyof PlasmicContactpage__ArgsType;
export const PlasmicContactpage__ArgProps = new Array<ArgPropType>();

export type PlasmicContactpage__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
};

export interface DefaultContactpageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContactpage__RenderFunc(props: {
  variants: PlasmicContactpage__VariantsArgs;
  args: PlasmicContactpage__ArgsType;
  overrides: PlasmicContactpage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__gfcHj)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__eg4Dl)}>
            <div className={classNames(projectcss.all, sty.freeBox__cpvLe)}>
              <div className={classNames(projectcss.all, sty.freeBox__hojnf)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__htRfn)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sincerely_sri_lankan_website/images/image4.png",
                    fullWidth: 1200,
                    fullHeight: 1200,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__sztz)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__y7Mp)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sincerely_sri_lankan_website/images/kindpng655303Png.png",
                      fullWidth: 466,
                      fullHeight: 715,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__xADhV)}>
                  <ParallaxWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.scrollParallax__vAbDu
                    )}
                    speed={-10}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nWsRm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w1Lsu
                        )}
                      >
                        {"Jane Doe"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fJqtq
                        )}
                      >
                        {"Member Committee Vice President - xx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gii0J
                        )}
                      >
                        {"+94 700 000 xxxx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wnuEw
                        )}
                      >
                        {"janedoe@aiesec.net"}
                      </div>
                    </div>
                  </ParallaxWrapper>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__lw4QJ)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rbLcB)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sincerely_sri_lankan_website/images/image4.png",
                    fullWidth: 1200,
                    fullHeight: 1200,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__j9WdX)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mNeuX)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sincerely_sri_lankan_website/images/kindpng655303Png.png",
                      fullWidth: 466,
                      fullHeight: 715,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___0UgI)}>
                  <ParallaxWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.scrollParallax__lCrJr
                    )}
                    speed={-10}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vzltW)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rg0Cb
                        )}
                      >
                        {"Jane Doe"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mhNgq
                        )}
                      >
                        {"Member Committee Vice President - xx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jpHxY
                        )}
                      >
                        {"+94 700 000 xxxx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rMBm
                        )}
                      >
                        {"janedoe@aiesec.net"}
                      </div>
                    </div>
                  </ParallaxWrapper>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__aFzXb)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___8HpYl)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sincerely_sri_lankan_website/images/image4.png",
                    fullWidth: 1200,
                    fullHeight: 1200,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__txJwa)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5ZzIz)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sincerely_sri_lankan_website/images/kindpng655303Png.png",
                      fullWidth: 466,
                      fullHeight: 715,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__vGrSx)}>
                  <ParallaxWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.scrollParallax__qv5Nd
                    )}
                    speed={-10}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__z5P6N)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iL69J
                        )}
                      >
                        {"Jane Doe"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k5Ahj
                        )}
                      >
                        {"Member Committee Vice President - xx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uhGk
                        )}
                      >
                        {"+94 700 000 xxxx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r1B6M
                        )}
                      >
                        {"janedoe@aiesec.net"}
                      </div>
                    </div>
                  </ParallaxWrapper>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__mpB4H)}>
            <div className={classNames(projectcss.all, sty.freeBox__esk2D)}>
              <div className={classNames(projectcss.all, sty.freeBox__fvnHf)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__c7RhI)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sincerely_sri_lankan_website/images/image4.png",
                    fullWidth: 1200,
                    fullHeight: 1200,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__mMvI)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__sU1Xw)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sincerely_sri_lankan_website/images/kindpng655303Png.png",
                      fullWidth: 466,
                      fullHeight: 715,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lzkZe)}>
                  <ParallaxWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.scrollParallax___6W64J
                    )}
                    speed={-10}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qWAW)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nWp2A
                        )}
                      >
                        {"Jane Doe"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5Vg9E
                        )}
                      >
                        {"Member Committee Vice President - xx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oJk1D
                        )}
                      >
                        {"+94 700 000 xxxx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qaUnH
                        )}
                      >
                        {"janedoe@aiesec.net"}
                      </div>
                    </div>
                  </ParallaxWrapper>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__nuRzP)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__c3Ji7)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sincerely_sri_lankan_website/images/image4.png",
                    fullWidth: 1200,
                    fullHeight: 1200,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__zbjn6)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__nxGcS)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sincerely_sri_lankan_website/images/kindpng655303Png.png",
                      fullWidth: 466,
                      fullHeight: 715,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___4A7VK)}
                >
                  <ParallaxWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.scrollParallax__t3Aej
                    )}
                    speed={-10}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__iaEly)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pInb6
                        )}
                      >
                        {"Jane Doe"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eoHA
                        )}
                      >
                        {"Member Committee Vice President - xx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__js9Tt
                        )}
                      >
                        {"+94 700 000 xxxx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__c0CsZ
                        )}
                      >
                        {"janedoe@aiesec.net"}
                      </div>
                    </div>
                  </ParallaxWrapper>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__eu3Ob)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bwsaj)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sincerely_sri_lankan_website/images/image4.png",
                    fullWidth: 1200,
                    fullHeight: 1200,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__s87ID)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__g2T0J)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sincerely_sri_lankan_website/images/kindpng655303Png.png",
                      fullWidth: 466,
                      fullHeight: 715,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__pjSyy)}>
                  <ParallaxWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.scrollParallax__j7CkO
                    )}
                    speed={-10}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fWpT)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yADr
                        )}
                      >
                        {"Jane Doe"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2LyN
                        )}
                      >
                        {"Member Committee Vice President - xx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h3GYx
                        )}
                      >
                        {"+94 700 000 xxxx"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sx8Hr
                        )}
                      >
                        {"janedoe@aiesec.net"}
                      </div>
                    </div>
                  </ParallaxWrapper>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header"],
  header: ["header"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactpage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactpage__VariantsArgs;
    args?: PlasmicContactpage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicContactpage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicContactpage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContactpage__ArgProps,
          internalVariantPropNames: PlasmicContactpage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContactpage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContactpage";
  } else {
    func.displayName = `PlasmicContactpage.${nodeName}`;
  }
  return func;
}

export const PlasmicContactpage = Object.assign(
  // Top-level PlasmicContactpage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),

    // Metadata about props expected for PlasmicContactpage
    internalVariantProps: PlasmicContactpage__VariantProps,
    internalArgProps: PlasmicContactpage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicContactpage;
/* prettier-ignore-end */
