// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: quDeq6xe5KMiTCfKiiLfyW
// Component: NU2jQ6vkLZ4_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName,
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions,
} from "@plasmicapp/react-web/lib/host";

import Header from "../../../.plasmic/Header"; // plasmic-import: gcpmzTU7M7CU/component
import { FlowingMenuContainer } from "../../FlowingMenu/FlowingMenuContainer"; // plasmic-import: 8A8p6Ubs46MZ/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: quDeq6xe5KMiTCfKiiLfyW/projectcss
import sty from "./PlasmicLCpage.module.css"; // plasmic-import: NU2jQ6vkLZ4_/css

createPlasmicElementProxy;

export type PlasmicLCpage__VariantMembers = {};
export type PlasmicLCpage__VariantsArgs = {};
type VariantPropType = keyof PlasmicLCpage__VariantsArgs;
export const PlasmicLCpage__VariantProps = new Array<VariantPropType>();

export type PlasmicLCpage__ArgsType = {};
type ArgPropType = keyof PlasmicLCpage__ArgsType;
export const PlasmicLCpage__ArgProps = new Array<ArgPropType>();

export type PlasmicLCpage__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  flowingMenuContainer?: Flex__<typeof FlowingMenuContainer>;
};

export interface DefaultLCpageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLCpage__RenderFunc(props: {
  variants: PlasmicLCpage__VariantsArgs;
  args: PlasmicLCpage__ArgsType;
  overrides: PlasmicLCpage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants,
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicLCpage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicLCpage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicLCpage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___7Oc9Q)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__njs9J)}>
            <div className={classNames(projectcss.all, sty.freeBox___056H5)}>
              <FlowingMenuContainer
                data-plasmic-name={"flowingMenuContainer"}
                data-plasmic-override={overrides.flowingMenuContainer}
                className={classNames(
                  "__wab_instance",
                  sty.flowingMenuContainer
                )}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__fL6Oy)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"50em"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/sincerely_sri_lankan_website/images/pngtreeMandalaDesignLineArtTraditional13535684Png.png",
                  fullWidth: 4096,
                  fullHeight: 4096,
                  aspectRatio: undefined,
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__myH36)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"50em"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/sincerely_sri_lankan_website/images/pngtreeLotusFlowerColoringPagesTo11046965Png.png",
                  fullWidth: 4267,
                  fullHeight: 4267,
                  aspectRatio: undefined,
                }}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "flowingMenuContainer"],
  header: ["header"],
  flowingMenuContainer: ["flowingMenuContainer"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  flowingMenuContainer: typeof FlowingMenuContainer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLCpage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLCpage__VariantsArgs;
    args?: PlasmicLCpage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLCpage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLCpage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLCpage__ArgProps,
          internalVariantPropNames: PlasmicLCpage__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicLCpage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLCpage";
  } else {
    func.displayName = `PlasmicLCpage.${nodeName}`;
  }
  return func;
}

export const PlasmicLCpage = Object.assign(
  // Top-level PlasmicLCpage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    flowingMenuContainer: makeNodeComponent("flowingMenuContainer"),

    // Metadata about props expected for PlasmicLCpage
    internalVariantProps: PlasmicLCpage__VariantProps,
    internalArgProps: PlasmicLCpage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "LC Page",
      description: "",
      ogImageSrc: "",
      canonical: "",
    },
  }
);

export default PlasmicLCpage;
/* prettier-ignore-end */
